TodoAspnetmvcUi/Components/EntriesListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TodoDomainEntities.Models;
using TodoDomainEntities.Models.Repository;

namespace TodoAspnetmvcUi.Components
{
	public class EntriesListViewComponent : ViewComponent
	{
		private readonly ITodoListRepository repository;

		public EntriesListViewComponent(ITodoListRepository repository)
		{
			this.repository = repository;
		}

		public IViewComponentResult Invoke(Entry entry)
		{
			return this.View(entry);
		}
	}
}

TodoAspnetmvcUi/Controllers/HomeController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TodoDomainEntities.Enums;
using TodoDomainEntities.Models;
using TodoDomainEntities.Models.Repository;

namespace TodoAspnetmvcUi.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ITodoListRepository repository;
        private readonly UserManager<IdentityUser> userManager;

        public HomeController(ITodoListRepository repository, UserManager<IdentityUser> userManager)
        {
            this.repository = repository;
            this.userManager = userManager;
        }

        public IActionResult Index() 
            => this.View(this.repository.TodoLists
                .Include(tdl => tdl.Entries.Where(e => e.Status != EntryStatus.Completed))
                .Where(tdl => tdl.Status == ListStatus.Show && tdl.UserId == this.userManager.GetUserId(this.User)));

        [Route("Details/{todolistId:long}")]
        public ViewResult Details(long todolistId)
        {
            return this.View(this.repository.TodoLists
                .Include(tdl => tdl.Entries.Where(e => e.Status != EntryStatus.Completed))
                .FirstOrDefault(tdl => tdl.Id == todolistId && tdl.UserId == this.userManager.GetUserId(this.User)));
        }

        [Route("TodoList/Edit/{todolistId:long}")]
        public ViewResult Edit(int todolistId)
        {
            return this.View(this.repository.TodoLists.FirstOrDefault(tdl => tdl.Id == todolistId && tdl.UserId == this.userManager.GetUserId(this.User)));
        }

        [HttpPost]
        [Route("TodoList/Edit/{todolistId:long}")]
        public IActionResult Edit(TodoList todolist)
        {
            if (todolist.UserId != this.userManager.GetUserId(this.User))
            {
                return this.RedirectToAction("Index");
            }

            if (this.ModelState.IsValid)
            {
                this.repository.EditTodoList(todolist);
                return this.RedirectToAction("Index");
            }

            return this.View(todolist);
        }

        [Route("TodoList/Create")]
        public ViewResult Create()
        {
            return this.View(new TodoList());
        }

        [HttpPost]
        [Route("TodoList/Create")]
        public IActionResult Create(TodoList todolist)
        {
            if (this.ModelState.IsValid) 
            {
                var userId = this.userManager.GetUserId(this.User);
                todolist.UserId = userId;

                this.repository.CreateTodoList(todolist);
                return this.RedirectToAction("Index");
            }

            return this.View(todolist);
        }

        [Route("TodoList/Delete/{todolistId:long}")]
        public IActionResult Delete(long todolistId)
            => this.View(this.repository.TodoLists.FirstOrDefault(tdl => tdl.Id == todolistId && tdl.UserId == this.userManager.GetUserId(this.User)));

        [HttpPost]
        [Route("TodoList/Delete/{todolistId:long}")]
        public IActionResult DeleteTodoList(long todolistId)
        {
            var todoList = this.repository.TodoLists.Include(tdl => tdl.Entries).FirstOrDefault(tdl => tdl.Id == todolistId);
            if (todoList == null || todoList.UserId != this.userManager.GetUserId(this.User))
            {
                return this.RedirectToAction("Index");
            }

            this.repository.DeleteTodoList(todoList);
            return this.RedirectToAction("Index");
        }

        [Route("TodoList/Hidden")]
        public ViewResult ShowHidden()
		    => this.View(this.repository.TodoLists
                .Include(tdl => tdl.Entries.Where(e => e.Status != EntryStatus.Completed))
                .Where(tdl => tdl.Status == ListStatus.Hide && tdl.UserId == this.userManager.GetUserId(this.User)));

        [Route("TodoList/Copy")]
        public IActionResult CopyList(long todolistId)
        {
            var todoList = this.repository.TodoLists.FirstOrDefault(tdl => tdl.Id == todolistId && tdl.UserId == this.userManager.GetUserId(this.User));
            
            if (todoList is not null)
            {
				this.repository.CopyTodoList(todolistId);
			}

            return this.RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
		{
			return this.View();
		}

	}
}

TodoAspnetmvcUi/Views/Home/Create.cshtml
@model TodoDomainEntities.Models.TodoList

@{
    Layout = "_Layout";
}

<partial name="_Editor" model='(@Model, "primary", "Create" , "Create")' />

TodoAspnetmvcUi/Views/Home/Delete.cshtml
@model TodoDomainEntities.Models.TodoList

@{
    Layout = "_Layout";
}

  <h3 class="bg-danger text-white text-center p-1">Are you sure you want to delete this TODO List: @(Model.Title)?</h3>

  <form asp-action="Delete" asp-controller="Home" method="post">
      <input type="submit" class="btn btn-danger" value="Delete" />
      <a class="btn btn-secondary" asp-controller="Home" asp-action="Index">Back</a>
  </form>

TodoAspnetmvcUi/Views/Home/Details.cshtml
@model TodoDomainEntities.Models.TodoList?

<h3 class="bg-info text-white text-center p-1">@(Model?.Title) Details</h3>
@foreach (var entry in Model?.Entries ?? Enumerable.Empty<Entry>())
{
	@await Component.InvokeAsync("EntriesList", entry)
}
<a class="btn btn-warning" asp-controller="Home" asp-action="Edit" asp-route-todolistId="@Model?.Id">Edit</a>
<a class="btn btn-secondary" asp-controller="Home" asp-action="Index">Back</a>
<a class="btn btn-secondary" asp-controller="Entry" asp-action="ShowCompleted" asp-route-todolistId="@Model?.Id">Show Completed</a>

TodoAspnetmvcUi/Views/Home/Edit.cshtml
@model TodoDomainEntities.Models.TodoList

@{
    Layout = "_Layout";
}

<partial name="_Editor" model='(@Model, "primary", "Edit" , "Edit")' />

TodoAspnetmvcUi/Views/Home/Index.cshtml
@model IQueryable<TodoList>

<partial name="_ListsInfo" model="@Model" />

TodoAspnetmvcUi/Views/Home/ShowHidden.cshtml
@model IQueryable<TodoList>

<partial name="_ListsInfo" model="@Model" />

TodoAspnetmvcUi/Views/Home/_Editor.cshtml
@model (TodoList todoList, string ThemeColor, string TitleText, string CallbackMethodName)

@{
    TodoList todoList = Model.todoList;
}

<h3 class="bg-@Model.ThemeColor text-white text-center p-1">@Model.TitleText a TODO List</h3>
<div class="row">
    <div class="col-md-4">
        <form asp-action="@Model.CallbackMethodName" asp-controller="Home" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (todoList.Id != 0)
            {
            <div class="form-group">
                <label asp-for="@todoList.Id" class="control-label"></label>
                <input asp-for="@todoList.Id" class="form-control" readonly />
            </div>
            }
            <div class="form-group">
                <label asp-for="@todoList.Title" class="control-label"></label>
                <input asp-for="@todoList.Title" class="form-control" />
                <span asp-validation-for="@todoList.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@todoList.Status" class="control-label"></label>
                <select asp-for="@todoList.Status">
                    <br /><option selected="selected" value="">Please select</option>
                    <option value="0">Show</option>
                    <option value="1">Hide</option>
                </select>
            </div>
            <div class="mt-2">
                <button type="submit" class="btn btn-@Model.ThemeColor">Save</button>
                <a class="btn btn-secondary" asp-controller="Home" asp-action="Index">Cancel</a>
                <a class="btn btn-danger btn-sm" asp-controller="Home" asp-action="Delete" asp-route-todolistId="@todoList.Id">
                    Delete
                </a>
            </div>
        </form>
    </div>
</div>

TodoAspnetmvcUi/Views/Home/_ListsInfo.cshtml
@model IQueryable<TodoList>
<AuthorizeView>

</AuthorizeView>
@foreach (var tdl in Model ?? Enumerable.Empty<TodoList>())
{
		<div class="d-flex bd-highlight">
			<div class="p-2 flex-grow-1 bd-highlight">
				<h3>@tdl.Title</h3>
				<p>@tdl.Entries.Count tasks</p>
			</div>
			<div class="p-2 bd-highlight">
			<a class="btn btn-info btn-sm" asp-controller="Home" asp-action="CopyList" asp-route-todolistId="@tdl.Id">
					Copy
				</a>
				<a class="btn btn-info btn-sm" asp-controller="Home" asp-action="Details" asp-route-todolistId="@tdl.Id">
					Details
				</a>
				<a class="btn btn-warning btn-sm" asp-controller="Home" asp-action="Edit" asp-route-todolistId="@tdl.Id">
					Edit
				</a>
				<a class="btn btn-danger btn-sm" asp-controller="Home" asp-action="Delete" asp-route-todolistId="@tdl.Id">
					Delete
				</a>
				<a class="btn btn-success btn-sm" asp-controller="Entry" asp-action="Create" asp-route-todolistId="@tdl.Id">
					Add Entry
				</a>
			</div>
			<div class="p-2 bd-highlight">
				<button class="btn btn-primary" data-bs-toggle="collapse" href="@("#collaps"+tdl.Id)" type="button" aria-expanded="false" aria-controls="@("collaps"+tdl.Id)">
					<i class="bi bi-chevron-double-down"></i>
				</button>
			</div>
		</div>
		<div class="collapse" id="@("collaps"+tdl.Id)">
			@foreach (var entry in tdl.Entries)
			{
				@await Component.InvokeAsync("EntriesList", entry)
			}
		</div>
}